### ISSUE TITLE
OpenNMS installation problem

### ISSUE THREAD

**Issue by Mac85** [fink/fink#130]
I installed fink but OpenNMS does not want to work. I reinstalled and reading errors I may have figured out the problem.
The problem java. He requires Java 1.5 or 1.6 instead I hava 1.8. And my observation correct? how can I do to fix it?
Following is the error message that I read at the end of the installation of OpenNMS

> java.check:
> [INFO] ------------------------------------------------------------------------
> [ERROR] BUILD ERROR
> [INFO] ------------------------------------------------------------------------
> [INFO] An Ant BuildException has occured: The following error occurred while executing this line:
> /sw/src/fink.build/opennms-1.8.16-32/opennms-1.8.16-1/source/build.xml:18: Your Java version (java.version = 1.8.0_45 java.vm.version = 25.45-b02) is not supported.  The
> build system is currently designed and tested to work with Java
> versions 1.5 and 1.6.  You can try to work around this error by
> modifying the java.check target in the build.xml file.

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An Ant BuildException has occured: The following error occurred while executing this line:
/sw/src/fink.build/opennms-1.8.16-32/opennms-1.8.16-1/source/build.xml:18: Your Java version (java.version = 1.8.0_45 java.vm.version = 25.45-b02) is not supported.  The
build system is currently designed and tested to work with Java
versions 1.5 and 1.6.  You can try to work around this error by
modifying the java.check target in the build.xml file.
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: The following error occurred while executing this line:
/sw/src/fink.build/opennms-1.8.16-32/opennms-1.8.16-1/source/build.xml:18: Your Java version (java.version = 1.8.0_45 java.vm.version = 25.45-b02) is not supported.  The
build system is currently designed and tested to work with Java
versions 1.5 and 1.6.  You can try to work around this error by
modifying the java.check target in the build.xml file.
    at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:131)
    at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:98)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more
Caused by: The following error occurred while executing this line:
/sw/src/fink.build/opennms-1.8.16-32/opennms-1.8.16-1/source/build.xml:18: Your Java version (java.version = 1.8.0_45 java.vm.version = 25.45-b02) is not supported.  The
build system is currently designed and tested to work with Java
versions 1.5 and 1.6.  You can try to work around this error by
modifying the java.check target in the build.xml file.
    at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:508)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:418)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:357)
    at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:118)
    ... 20 more
Caused by: /sw/src/fink.build/opennms-1.8.16-32/opennms-1.8.16-1/source/build.xml:18: Your Java version (java.version = 1.8.0_45 java.vm.version = 25.45-b02) is not supported.  The
build system is currently designed and tested to work with Java
versions 1.5 and 1.6.  You can try to work around this error by
modifying the java.check target in the build.xml file.
    at org.apache.tools.ant.taskdefs.Exit.execute(Exit.java:142)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:357)
    at org.apache.tools.ant.Target.performTasks(Target.java:385)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:416)
    ... 29 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11 seconds
[INFO] Finished at: Sat Jun 25 01:22:39 CEST 2016
[INFO] Final Memory: 63M/384M
[INFO] ------------------------------------------------------------------------
[ERROR] child exited with value 1
### execution of /tmp/fink.BDAUz failed, exit code 1

Removing runtime build-lock...
Removing build-lock package...
/sw/bin/dpkg-lockwait -r fink-buildlock-opennms-1.8.16-32
(Reading database ... 6228 files and directories currently installed.)
Removing fink-buildlock-opennms-1.8.16-32 ...
Failed: phase compiling: opennms-1.8.16-32 failed

Before reporting any errors, please run "fink selfupdate" and try again.
Also try using "fink configure" to set your maximum build jobs to 1 and
attempt to build the package again.
If you continue to have issues, please check to see if the FAQ on Fink's 
website solves the problem.  If not, ask on one (not both, please) of
these mailing lists:

```
The Fink Users List <fink-users@lists.sourceforge.net>
The Fink Beginners List <fink-beginners@lists.sourceforge.net>,
```

with a carbon copy to the maintainer:

```
Benjamin Reed <opennms@fink.raccoonfink.com>
```

Note that this is preferable to emailing just the maintainer directly,
since most fink package maintainers do not have access to all possible
hardware and software configurations.

Please try to include the complete error message in your report.  This
generally consists of a compiler line starting with e.g. "gcc" or "g++"
followed by the actual error output from the compiler.

Also include the following system information:
Package manager version: 0.39.3
Distribution version: selfupdate-rsync Sat Jun 25 01:16:18 2016, 10.11, x86_64
Trees: local/main stable/main stable/crypto unstable/main unstable/crypto
Xcode.app: 7.3.1
Xcode command-line tools: 7.3.1.0.1.1461711523
Max. Fink build jobs:  4

**Comment by akhansen** [comment]
This has absolutely nothing to do with the fink code.  Issues with packages should be filed on one of our mailing lists

- fink-users@lists.sourceforge.net

- fink-beginners@lists.sourceforge.net

- fink-devel@lists.sourceforge.net

or on our packaging bug tracker

https://sourceforge.net/p/fink/bugs/
